### ISSUE TITLE
Footprints where they shouldn't

### ISSUE THREAD

**Issue by mrcrashmer** [Rivmun/FootprintParticle#19]
glass and concrete (maybe others) leave traces and it is not possible to disable it in the config (fabric 1.19.4)
On version 1.19.3, I remember for sure that some blocks did not generate traces, and now they appear there. :(

**Comment by Rivmun** [comment]
Which mod version are you play with?
I tested 0.2.3 on 1.19.4 and it's working fine.
Just type _minecraft:grass_block_ in Block Excluded and footprints will never gen on it.

![image](https://user-images.githubusercontent.com/113169310/233958764-768f3fbb-fe94-47a1-a3e1-623cd4263f4d.png)
