### ISSUE TITLE
Generating too many particles in mob farm area

### ISSUE THREAD

**Issue by Rivmun** [Rivmun/FootprintParticle#3]
Will make some lag.
Limited max amount in same chunks maybe fix it?

**Comment by MikhailTapio** [comment]
Also try adding a blacklist of LivingEntities generating footprint particles.

**Comment by Rivmun** [comment]
> Also try adding a blacklist of LivingEntities generating footprint particles.

Already in config screen on v0.1.0.
The option name is "Mob Excluded“. Try to type in "modid:mobid" in this list then the mob will no generate footprint.

**Comment by Rivmun** [comment]
Maybe no fixed because particle can be automatic disappear, and now it will not be flickered to affects visual experience.
