### ISSUE TITLE
Suggestion: Make slow entities print less footprints over time

### ISSUE THREAD

**Issue by xFirefalconx** [Rivmun/FootprintParticle#57]
In a mod called "Untamed Wilds" there are turtles. They walk slowly but still print the same large footprints. I wonder if there could be a slider to make specific entities print less particles/s to make it look less like they are just leaving one large trail. Or maybe they just need to be scaled down in that case. No idea. New to the mod. 
(1.18.2 btw)

**Comment by Rivmun** [comment]
Using a config called 'Footprint Size' which can control footprint size of specific mob, or 'Mob Interval' which can control foot printing frequent of specific mob. Remember take a look to the option tooltips I wrote.

**Comment by xFirefalconx** [comment]
Ah thank you I wasn't aware of that indeed. I just found the option when you wrote. How do I figure out the entity names exactly?
