### ISSUE TITLE
Incompatibility with RandomMobSizes

### ISSUE THREAD

**Issue by tristankechlo** [Rivmun/FootprintParticle#71]
Any modversion of 2.1 or higher from RandomMobSizes causes a `NoClassDefFoundError`.   
  
The package structure of my mod changed slightly in the latest updates:  
Old: `com.tristankechlo.random_mob_sizes.mixin_access.MobMixinAddon`  
New: `com.tristankechlo.random_mob_sizes.mixin_helper.MobMixinAddon`

**Comment by tristankechlo** [comment]
The update was published to the versions 1.18.2, 1.19.3, 1.19.4, 1.20.1, 1.20.4 and 1.20.6  
No further changes to the package structure are planned, so it's safe to adapt for a longer timespan :+1:

**Comment by Rivmun** [comment]
Wait, where 1.19.2's RandomMobSizes v2.1?

-- It my main maintenance (and playing) version if you wonder why I ask🤔

**Comment by tristankechlo** [comment]
Sadly no new version for 1.19.2 (yet)

I just had the issue reported to me, and wanted to notify you.  
But in the end it's up to you for which versions you adjust your mod

**Comment by Rivmun** [comment]
Sure glad to see this notice from you and I'll fix the compat for RandomMobSizes,


and if 1.19.2 has v2.1 is better (just a beg jokingly ww
