### ISSUE TITLE
new update crashes on startup

### ISSUE THREAD

**Issue by lilsherm09** [Rivmun/FootprintParticle#79]
i added the newest update to my client and now it crashes on startup, when backporting to the older update its completely fine.

| Mod ID: 'minecraft', Requested by: 'footprintparticle', Expected range: '[1.19.4,1.20.1)', Actual version: '1.20.1'
  | 3 lines
| [12:19:12] [main/ERROR]: Skipping early mod setup due to previous error
  | 1 line

**Comment by Rivmun** [comment]
What loader you use? Seems it just because Minecraft version doesn't in range that mod.toml or fabric.mod.json expected. Try to replace that with a "*"

**Comment by Rivmun** [comment]
https://github.com/Rivmun/FootprintParticle/commit/099a1aa1354403ce2b0afe7710c4d7f13c1e019b
I made a small patch and reuploaded 0.5.2-1.20 file to distribute site. Download new file will fix this issue
